### ISSUE TITLE
Add examples on how to setup proxies/Tor in the documentation

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#125]
Users of the package should be encouraged to use proxies/Tor, and providing a few working examples should help.

**Comment by stefanct** [comment]
There was one in the readme actually but it has been removed without a replacement in the documentation. See https://github.com/scholarly-python-package/scholarly/tree/fe574671e460bd4a57817804ad637c74d582d67d#using-proxies

**Comment by DGhose-2** [comment]
Further details from and regarding the code in closed issue 120 (https://github.com/scholarly-python-package/scholarly/issues/120) should be added, given that this issue is likely to surface for practically anyone using Scholarly.

Given the need to troubleshoot it would be nice to get more clarity on how exactly one is encouraged to go about circumventing the IP ban. That is, code should be documented that tries proxies and finally returns as the last one, a working proxy, which can then be set in ```use_proxy``` and will work (for a little while).

Also, FreeProxy clearly isn't great anymore--I reached 40 failed proxies before I gave up. What if we have another proxy or VPN (e.g. a paid service like ProtonVPN or ExpressVPN), how can we get this to work? Documentation on that would be good too i.e. extracting IP, port number, etc.

I think some attention on this would be worthwhile given the currently mentioned options (FreeProxy, Tor) aren't working well anymore.

**Comment by ipeirotis** [comment]
If you have a proxy, use the `use_proxy` command with your own proxy details.

**Comment by DGhose-2** [comment]
How should we find out from our proxy what the http and https arguments for ```use_proxy``` are? And if the proxy works for surfing Google Scholar in the regular browser, should it work with Scholarly too or do we still expect trial and error. Or is Tor a better/easier/faster way to go? (Here there is a minimal example for using Tor: https://github.com/scholarly-python-package/scholarly/issues/86. But some more detail on finding http and https and setting them up to refresh would be appreciated.)

These questions are worth making some comments on since researchers may be very interested in using Scholarly but lack experience with proxies and Tor.

**Comment by DGhose-2** [comment]
Btw regarding the code in https://github.com/scholarly-python-package/scholarly/issues/120, this might be substantially sped up if you can prevent the choice from including any proxies tried already
