### ISSUE TITLE
Proposed new syntax

### ISSUE THREAD

**Issue by silvavn** [scholarly-python-package/scholarly#135]
The current syntax has problems to delete the session instance (aka, it is never really closed). Using `with` would solve many problems since the `__enter__` and `__exit__` functions are properly executed. Thus, I am proposing the following change to the `scholarly` base syntax:

```python
from scholarly import scholarly

with scholarly() as sc:
    tor_sock_port = 9150
    tor_control_port = 9151
    sc.use_tor(tor_sock_port, tor_control_port, "")
    authors = [a for a in sc.search_author('')]
```
Thoughts?

**Comment by ipeirotis** [comment]
Makes sense.

In terms of avoiding network issues, I think we should also try to take out from Author and Publication and network calls, and use Author and Publication purely as data containers.

Perhaps we can change the Author.fill() and Publication.fill() functions to be `sc.fill_author(Author)` and `sc.fill_publication(Publication, sections=[...])`. 

That would make it more explicit in the code when the network connection is being used, and there is no need to keep the connections open when the users do not need to fetch more data, but rather use the downloaded Author and Publication objects.

**Comment by ipeirotis** [comment]
@silvavn Here is a related proposal:

I propose the Author and Publication objects to be pure data containers, with no parsing logic within them. I gave a shot at https://github.com/scholarly-python-package/scholarly/blob/develop/scholarly/data_types.py to introduce such simple data types, with the main goal being to document the exact semantics of each field, so that we do not confuse the meaning of the various similarly sounding fields.

Then, we can also create two objects AuthorParser, PublicationsParser, with their goal being taking as input DOM object, and returning back the related Author and Publications objects. These classes should not have any network calls in them, just parsing logic. DOM in, Author/Publication out.

Then, the navigator class has two objectives. One is to successfully complete the "getPage(URL)" calls, and another is to provide abstractions for all the necessary URL calls that we need (search for authors, search for publication, search for paper citing a publication, and so on). If we want to be too strict, we can even split that layer in two (the "tor/proxy/getpage" stuff, and then all the abstractions for searching for various URLs)

Let me know what you think.

**Comment by silvavn** [comment]
I agree with that. We should definitely have separate scripts that do the parsing. That way if anything changes its easier to work on just the parser and not the whole navigator script.

**Comment by ipeirotis** [comment]
Many of these issues were fixed with the ProxyGenerator addition.
