### ISSUE TITLE
Sort by year (instead of "cited by") for search by author ID

### ISSUE THREAD

**Issue by michaelfromyeg** [scholarly-python-package/scholarly#155]
By [default](https://scholar.google.com/citations?hl=en&user=EmD_lTEAAAAJ) it semes an author's page displays the publications that have been cited the most times first; if you click the year link, you're then able to get the author's most recent publications. The URL changes slightly: https://scholar.google.com/citations?hl=en&user=EmD_lTEAAAAJ&view_op=list_works&sortby=pubdate

Is there any way this could be built in the new `scholarly.search_author_id` (#148) function? Some sort of 'sortby' parameter would be really handy (especially for my [use case](https://github.com/michaelfromyeg/rECEsearch)).

**Comment by Nicholas-Lewis-USDA** [comment]
Why not just filter your self?

```
search_query = scholarly.search_author("{author's name}")
author_info = next(search_query).fill()
for pub in author_info.publications:
    if int(pub.bib['cites']) > 100:
        print(pub.bib['title'])

```

Also reference https://stackoverflow.com/questions/45781760/sorting-multiple-dictionary-dimensions-at-once to sort the results that come at you.

**Comment by michaelfromyeg** [comment]
Sorry maybe I wasn't clear -- I'm not looking to filter. I'm looking to get the author's most recent publications instead of their most popular (which is what is currently yielded).

Number of citations don't matter in this case.

**Comment by Nicholas-Lewis-USDA** [comment]
If you don't mind playing a little with the code yourself.

in author.py 
line 11 > add `_CITATIONAUTH_FILTER = '/citations?hl=en&user={0}&view_op=list_works&sortby=pubdate'`
line 16, after `"none"` enter `,my_filter="none"`

line 97 you need to change this so that if you submit a "yes" for my_filter it will use the new line we added in line 11.
line 189 (prior to your changes) change to match your changes you did on line 97 and on.

when you submit your changes you will likely need to submit it like search_author(author_name,"none","yes") as you need to ensure none is left by default in the code if I am reading it correctly)

I think those changes would allow you to apply the google filter to search by publication date.

Sorry I don't really have more time to test / play with it more than this.

**Comment by silvavn** [comment]
@michaelfromyeg a quick dirty way to do that would be going into line 10 of `author.py` and add `&sortby=pubdate` on your local scholarly. 

To implement your functionality you would have to add an optional parameter to the constructor of the `Author` (and consequently the search functions) class and format the url accordingly. 

If you would like to suggest a PR on the `developer` branch we could probably merge it.

**Comment by michaelfromyeg** [comment]
Sounds good! I'll give it a go this weekend. Thanks for the quick fix as well, appreciate it.

**Comment by ipeirotis** [comment]
Version v.1.0.6 adds this functionality:

```python
author = scholarly.search_author_id(id = 'PA9La6oAAAAJ', filled = True, sortby = "year", publication_limit = 5)
scholarly.pprint(author)
```
