### ISSUE TITLE
Does scholarly searches with proxy take that much time?

### ISSUE THREAD

**Issue by felipeboffnunes** [scholarly-python-package/scholarly#180]
I'm using proxies from FreeProxy and another source, and I'm changing proxies correctly. But, it takes about 10 to 20 minutes for a result without a captcha or failed requests. Does it normally take that much time? Am I missing something?

First use of scholarly, using my own ip, was fine, but then it blocked my ip and I started using the proxies, and it started taking too much time to load a search.

**Comment by felipeboffnunes** [comment]
From what I've seen, using proxies and finding one request that does not get a captcha takes a very long time. I'm solving the captchas for now, but would be good to try to improve the user agent headers with more info to try to surpass the bot detection.

**Comment by silvavn** [comment]
Hi Felipe,
To answer your first question: yes. After so many calls you are most likely gonna be blocked. See #141.  Also, because so many people use scholarly, TOR and other proxies are flooded.

One option is to use selenium and solve the captchas yourself. See my personal branch or @janruh branch for a selenium implementation. There, both of us have implemented the header optimization.

Finally, we do accept PR contributions, just fork the `main` branch and target the `developer` branch with your PR
