### ISSUE TITLE
Contribution: new field pub.bib.author_id

### ISSUE THREAD

**Issue by cnantoninor** [scholarly-python-package/scholarly#186]
Hello Scholarly team,

thank you for your work it has been very useful for a side project I just did.

I would like to contribute a new feature that I added during that project. I have added a new field, `author_id` returned while searching for publications, i.e. `search_pubs` methods.

The new field contains a list of `author_id` positionally matching with the `author` field.
Example from the test with highlighted the new `author_id` field:

```
query = 'Creating correct blur and its effect on accommodation'
        results = scholarly.search_pubs(query)
        pubs = [p for p in results]
        self.assertGreaterEqual(len(pubs), 1)
        f = pubs[0].fill()
        self.assertTrue(f.bib['author'] == u'Cholewiak, Steven A and Love, Gordon D and Banks, Martin S')
        **self.assertTrue(f.bib['author_id'] == ['4bahYMkAAAAJ', '3xJXtlwAAAAJ', 'Smr99uEAAAAJ'])**
        self.assertTrue(f.bib['journal'] == u'Journal of vision')
        self.assertTrue(f.bib['number'] == u'9')
        self.assertTrue(f.bib['pages'] == u'1--1')
        self.assertTrue(f.bib['publisher'] == u'The Association for Research in Vision and Ophthalmology')
        self.assertTrue(f.bib['title'] == u'Creating correct blur and its effect on accommodation')
        self.assertTrue(f.bib['url'] == u'https://jov.arvojournals.org/article.aspx?articleid=2701817')
        self.assertTrue(f.bib['volume'] == u'18')
        self.assertTrue(f.bib['year'] == u'2018')
```

I have a patch file but please LMK what is the best way to contribute if you are interested.

Thanks,
Antonino

**Comment by silvavn** [comment]
Hi @cnantoninor the best way to contribute to this repository is to fork it and implement the modifications on your fork. Once they are passing the tests you can issue a push request against the `develop` branch. We will review the code and if everything is ok we will merge the PR

**Comment by cnantoninor** [comment]
See https://github.com/scholarly-python-package/scholarly/pull/187

**Comment by Ardillen66** [comment]
Hi, I found a bug due to this new feature. Since the issue is still open, I am posting it here instead of opening a new issue.

When generating BibTex for a publication and there are None values in the `author_id ` list you get a `TypeError`. Looking at the code, I found this is due to string join in the `.bibtex()` method of `Publication`.

As a sidenote. Are these author IDs relevant to a BibTex entry? As these IDs only really make sense within Google Scholar.

**Comment by jvlmdr** [comment]
@Ardillen66 +1 for this problem, it broke the `Publication.bibtex` property for me. As described above, the bug occurs when the author_id list contains `None` elements: https://github.com/scholarly-python-package/scholarly/blob/13b203a51c8c31736c5313f1082ecbd18c925569/scholarly/publication.py#L312

To reproduce:
```python
query = '"Tracklet Association Tracker: An End-to-End Learning-based Association Approach for Multi-Object Tracking"'

from scholarly import scholarly
publication = scholarly.search_single_pub(query)
bibtex = publication.bibtex
```

**Comment by s1mar** [comment]
Same, pub.bibtex is broken now :(

` converted_dict['author_id'] = ', '.join(converted_dict['author_id'])
KeyError: 'author_id'`

**Comment by s1mar** [comment]
Problem: You fetch an author and their publications but when you try to get the BibTeX, you get parsing errors because of missing author_ids. 
Workaround:
I exposed the URL in the publication class, then used the search_pub method on this URL to get a new instance of the publication, and Voila! Problem Solved, it had the missing keys, like author_id

` pub = author.publications[1]
    url = pub.url
    pub = next(scholarly.search_pubs(url))
    print(pub.bibtex)`

**Comment by s1mar** [comment]
**Problem**
When you access the publications through an Author, you run into this error, especially the key not found in converted_dict[] variant. 
**Possible Workaround**
- Expose the url in the publications class. I exposed it as a getter property.
- Add checks for author_id key not existing and the value of this key not being of NoneType.
- Now, use the url with the search_pub function to get a new instance of the publication you want
- With this new instance, you should be able to get the BibTex

You might be wondering that since I've put checks in place then why get a new publication instance using the url ?, well there is a reason for that: The original publication instances gotten via Author has something else wrong with thems as well, for the checks do get you beyond that error but then I was getting a new BibTex Parser error.
![dev](https://user-images.githubusercontent.com/16931768/98507887-7e6e5f00-222c-11eb-930d-92c2e9024a83.jpg)

**Comment by ipeirotis** [comment]
We are working on version 1.0 now, which will refactor many of these.

**Comment by ipeirotis** [comment]
The version v.1.0 returns bac the author ids of the authors.

```python

from scholarly import scholarly
from scholarly import ProxyGenerator

pg = ProxyGenerator()
proxy = '<your proxy>'
pg.SingleProxy(http = proxy, https = proxy)
scholarly.use_proxy(pg)

search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
pub = next(search_query)
scholarly.pprint(pub)
```

The `pub` object contains the `author_id` field, with a list of the IDs of the authors, as they appear in the search results.

```
{'author_id': ['4bahYMkAAAAJ', 'ruUKktgAAAAJ', ''],
 'bib': {'abstract': 'Humans can judge from vision alone whether an object is '
                     'physically stable or not. Such judgments allow observers '
                     'to predict the physical behavior of objects, and hence '
                     'to guide their motor actions. We investigated the visual '
                     'estimation of physical stability of 3-D objects (shown '
                     'in stereoscopically viewed rendered scenes) and how it '
                     'relates to visual estimates of their center of mass '
                     '(COM). In Experiment 1, observers viewed an object near '
                     'the edge of a table and adjusted its tilt to the '
                     'perceived critical angle, ie, the tilt angle at which '
                     'the object',
         'author': ['SA Cholewiak', 'RW Fleming', 'M Singh'],
         'pub_year': '2015',
         'title': 'Perception of physical stability and center of mass of 3-D '
                  'objects',
         'venue': 'Journal of vision'},
 'citedby_url': '/scholar?cites=15736880631888070187&as_sdt=5,33&sciodt=0,33&hl=en',
 'eprint_url': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
 'filled': False,
 'gsrank': 1,
 'num_citations': 23,
 'pub_url': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
 'source': 'PUBLICATION_SEARCH_SNIPPET',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DPerception%2Bof%2Bphysical%2Bstability%2Band%2Bcenter%2Bof%2Bmass%2Bof%2B3D%2Bobjects%26hl%3Den%26as_sdt%3D0,33&citilm=1&json=&update_op=library_add&info=K8ZpoI6hZNoJ&ei=ApfRX6W-A46CywTRt52ACQ',
 'url_scholarbib': '/scholar?q=info:K8ZpoI6hZNoJ:scholar.google.com/&output=cite&scirp=0&hl=en'}
```

Notice that if you `fill` the object, you may retrieve more authors, and you may end up with more elements in the `author` field of the `bib` field of the publication than the elements in the `author_id`
