### ISSUE TITLE
Query results have Source: PublicationSource.PUBLICATION_SEARCH_SNIPPET

### ISSUE THREAD

**Issue by stanleyrhodes** [scholarly-python-package/scholarly#291]
```
from scholarly import scholarly
import json

search_query = scholarly.search_pubs('"hierarchy they mean" AND social')  # ~4 items
sq_array = []
for i in search_query:
    sq_array.append(i)

output_to_file = json.dumps(sq_array[1])
output_to_file

# TypeError: Object of type PublicationSource is not JSON serializable
```

So what's going on?

```
{'container_type': 'Publication',
 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 1>,
 'bib': {'title': 'The experimenting university', ...
```

Ok, but shouldn't that just be either "1" or "PUBLICATION_SEARCH_SNIPPET" as a value for the 'source' key? Is returning this object intentional, and does it serve some purpose? Or is there some other issue? Obviously not ideal for this use case of putting the array straight into JSON.

I didn't find the entry for this in the docs to really clarify:
https://scholarly.readthedocs.io/en/latest/DataTypes.html?highlight=publicationsource#scholarly.data_types.PublicationSource

**Comment by ipeirotis** [comment]
Not sure why this is flagged as a problem. It is an Enum, to define the type of the result (whether the publication is coming from an author page, or from the publication snippet).

If the problem is the json serialization, then I would recommend doing a `del i['source']` before appending it to the array.

**Comment by stanleyrhodes** [comment]
I relooked into the sources of my confusion. Perhaps I am missing something, but doesn't every example in the quickstart documentation show that the source is given as a string?
https://scholarly.readthedocs.io/en/latest/quickstart.html#methods-for-scholar
and most relevant to my example: https://scholarly.readthedocs.io/en/latest/quickstart.html#search-pubs

I didn't consider that maybe the documentation is a bit behind. I refer to the quickstart a lot in trying to get scholarly to work for my needs (no success yet, but I persist). I didn't know about Enums, thank you.

**Comment by ipeirotis** [comment]
When you pretty print the response indeed the enum shows as a strong. I do not think that the documentation is off, but we do not really have doctests in place to ensure the accuracy of the documentation examples.

**Comment by stanleyrhodes** [comment]
This would probably be better as a new discussion topic rather than extending my old and closed bug report. 

@abubelinha I found it very hard to understand Scholarly in part because I had to understand much better what Google Scholar was actually doing. The way to start thinking about Scholarly is to understand what Google Scholar is giving you in a search without using Scholarly. Scholarly has to scrape all the data it provides. The snippet doesn't provide that much info. Why does Scholarly bother to only return the snippet, not the full info? Because GS is very defensive about requests, and will block repeated requests in no time.

The documentation is a bit bare bones in explaining the big picture. And it's also bare bones in explaining how to request and manipulate article information; for some reason the documentation seems mostly focused on authors. But the reason for doing only snippets is mentioned in the documentation:

> By default, scholarly returns only a lightly filled object for publication, to avoid overloading Google Scholar. If necessary to get more information for the publication object, we call this method.

By "this method" it means `fill`. But first, let's try to see what's happening.

If you do a search for a topic, GS gives you a page of results that are "snippets." Meaning, they are incomplete and truncated, and don't have all the bib information. They don't have the full journal title if the journal title is long, they don't have volume, and they don't have pages.

For example, this search:
https://scholar.google.com/scholar?hl=en&q=adaptive+fraud+detection

Gives this as one of its entries (I've stripped the links out):
Adversarial learning in credit card fraud detection
MF Zeager, A Sridhar, N Fogal, S Adams… - 2017 Systems and …, 2017 - ieeexplore.ieee.org
… The contributions of this paper are the following: • Introducing an adaptive fraud detection
system that utilizes repeated games in the form of a feedforward model and incorporates the …
Save Cite Cited by 64 Related articles All 2 versions

Notice how little info that is. Authors have a ... and the journal title has a ... Truncated and rather useless. It's terrible, but GS is to blame, for a design decision long ago that has never been revisited. To get the full, useful information, GS has to be queried on a per-item basis, as you would if you clicked on that "Cite" link yourself as a normal user. That means an automated query and scrape will need to not only do one query per page of results, but an additional query for every item on that page. This will get you blocked very quickly without using a good proxy service. And this goes back to why Scholarly is only providing the snippet.

We can request the detailed information by using the `fill `method on the `Publication` object.

https://scholarly.readthedocs.io/en/latest/scholarly_user.html
https://scholarly.readthedocs.io/en/latest/DataTypes.html#scholarly.data_types.Publication

I must admit, I struggled with using the library to retrieve the data for my study (a lit review starting with ~11k articles via Scholarly). Also, I used it in combination with Zotero, but that's a whole other story. So I am not someone very familiar with the internals, I am just a researcher who managed to get it to work just enough to get the job done, and who has now forgotten some of the finer points of that effort. I hope this info helps get you started. And I will be making my code for my project publicly available on Github when my coauthors and I submit for publication, which should be very soon.

**Comment by abubelinha** [comment]
Thanks a lot for your detailed explanation. IMHO **it deserves to be put in the documentation**.

By the time you answered here I was already diving into some other issues, discovered the `fill` method and also discovered [your entry in discussions](https://github.com/scholarly-python-package/scholarly/discussions/430) which was so useful (I must admit I always forget to look at that section because it uses to be empty in many github repositories).

So I tried scrapeapi like you, and it worked so well. 
I got my ~1K pubs and stored that output in a file ... just to realize all that you have explained: it is mostly incomplete/truncated stuff. And that consumed 1/3 of my scrapeapi credits. So I didn't dare to try `scholarly.fill(pub)`

Bottom line: this won't be enough but in my case I have no budget for paying a scraping api.
But at least this will save me a lot of work in terms of browsing GS pages. I can put this into a spreadsheet to filter out those pubs which are false positives.

One python-noob side question. 
I should have used pickle or something alike, but I didn't realize and treated my pubs as strings.
i.e. I saved them into a .txt file like this:
```Python
with open(filename,"w",encoding="utf-8") as f:
   for pub in scholarly.search_pubs(query = "my query"):
      file.write(str(pub)+"\n") 
```
But it is not that easy to reuse these lines now (if I ever want to try `fill`): they were not json strings as I blindly assumed when I quickly stored them just for simple caching purposes.
I actually wonder how to turn one of them back into a [`publication`](https://scholarly.readthedocs.io/en/stable/quickstart.html#search-for-articles-publications-and-return-generator-of-publication-objects) object which I can [`fill`](https://scholarly.readthedocs.io/en/stable/quickstart.html#fill). Any suggestions?

I'll keep an eye on your code when you post it. 
BTW, I suppose you will cite scholarly ... be aware that [citation link is outdated](https://github.com/scholarly-python-package/scholarly/issues/501) (although you might have used that version):

Thank you very much again !!!
