### ISSUE TITLE
Error message appearing when Scholarly imports fake-useragent

### ISSUE THREAD

**Issue by danuccio** [scholarly-python-package/scholarly#313]
Following the release of the updated versions of scholarly I have been getting the following error message. 

`Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/xyz/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
`

The package still seems to be able to collect data from Google Scholar, although I am uncertain if this error may be relevant elsewhere and cause problems somewhere else like when using proxies or not getting blocked when doing larger data collections.

I am aware another user posted a similar issue yesterday and that it was closed, but I did not see a solution or any mention of what problems this error may cause. Apologies for any redundancy or if I missed something obvious.

**Comment by Paradoxdruid** [comment]
This issue was identified in the fake-useragent issue tracker, and it looks like a fix is waiting for merge:  https://github.com/hellysmile/fake-useragent/pull/110  

I opened and closed the issue yesterday (sorry!), realizing it was better directed to the fake-useragent repo.  👍

**Comment by danuccio** [comment]
@Paradoxdruid Thank you for your assistance! That does seem to fix the issue.

**Comment by dbogatov** [comment]
@danuccio  Can we keep this one open until https://github.com/hellysmile/fake-useragent/pull/110 is merged into scholarly?
I want to track when I can upgrade the package.
So far this is a blocking issue.

**Comment by ipeirotis** [comment]
This seems to be an issue. Unclear right now where we use the library in the code. Perhaps we can remove it?

**Comment by arunkannawadi** [comment]
I've seen this error as well, although it has never affected the performance. I think the easiest is to identify where this exception occurs and catch it until it is fixed in fake-useragent.

**Comment by arunkannawadi** [comment]
Update: There are no actual exceptions thrown, but just the traceback is printed. The fake-useragent repo doesn't seem to be maintained anymore and we shouldn't expect the patch to be merged any time soon, so I don't see the point of keeping this issue open here. However, since this is not an exception to catch and doesn't affect the way `scholarly` works, I don't suppose this issue should be a blocker to anyone.

The traceback is printed the first time `UserAgent()` is called [here](https://github.com/scholarly-python-package/scholarly/blob/994a247cc4bdbc1a14ccb5e544ea6dc6045f27f7/scholarly/_proxy_generator.py#L368) and this internal error occurs when there is no cached data available. I wouldn't want to remove it, since having a user agent in the header minimizes the chances of getting blocked.

**Comment by arunkannawadi** [comment]
Closing this issue (again) because:

1. The error message appears from a dependency, and not from `scholarly` and hence outside the scope.
2. No actual Python exceptions are raised but only a traceback message is printed. It is certainly misleading but does not crash any applications as a result.
3. This appearance of traceback cannot be avoided by back-porting to an earlier version of `fake-useragent`.
4. `fake-useragent` does not seem to be actively maintained and the submitted patch to fix this bug is not going to get in any time soon.

Given the lack of maintenance, we may want to move away from the package, but removing the dependency on `fake-useragent` is not pressing, since it works fine and does not affect the performance of `scholarly`.

@dbogatov - since there is no real error Python error raised, it should not be a blocker for your application. You should be able to use `scholarly` and ignore the error message.

**Comment by arunkannawadi** [comment]
This appears to be a good solution to suppress this misleading message when importing fake-useragent:
https://thesmithfam.org/blog/2012/10/25/temporarily-suppress-console-output-in-python/
