### ISSUE TITLE
Tor_Internal: why not take_ownership?

### ISSUE THREAD

**Issue by alexanderustinov** [scholarly-python-package/scholarly#393]
There is a line in `_proxy_generator.py`, that comments out `take_ownership=True` for `stem.process.launch_tor_with_config` method and mentions "# Taking this out for now, as it seems to cause trouble".
https://github.com/scholarly-python-package/scholarly/blob/0175a8d93dd8e03af98a6391715226c8c7601a51/scholarly/_proxy_generator.py#L295

What were the troubles, i wonder?

With this line uncommented the spawned tor process gets terminated after program exit. Otherwise one have to hunt it (via netstat or via psutil module) and kill it.

**Comment by ipeirotis** [comment]
It has been a while. I think that if we used the `take_ownership` option, the python process for scholarly was not fully terminating, and kept hogging the port.

In any case, the `tor_internal` is marked as deprecated right now, so I will mark this as a "wont fix". 

If someone wants to use Tor, by far the better idea is to have a separate Tor process running with the official client. The `stem` library has not been updated for almost 3 years now.

And it is possible to use the external Tor proxy using the `singleProxy` approach (instead of the `tor_external`), without losing much functionality.

**Comment by alexanderustinov** [comment]
> It has been a while. I think that if we used the `take_ownership` option, the python process for scholarly was not fully terminating, and kept hogging the port.

I observe the opposite: when the option is commented out (default is `False`) tor process stays alive after program's successful termination. If i uncomment `take_ownership=True`, it terminates with python program. I can imagine the case when hung up tor-proxy process can somehow affect graceful termination of python program (hanging of certain scholarly methods, really, happened to me without any proxy used; but as the debugging of such semi-random hangs is not straightforward, currently i have failed to get anything meaningful to report as a bug)
> In any case, the `tor_internal` is marked as deprecated right now, so I will mark this as a "wont fix".
> 
> If someone wants to use Tor, by far the better idea is to have a separate Tor process running with the official client. The `stem` library has not been updated for almost 3 years now.

Agree on both. Is it a good idea to slowly move `Tor_External` to `Tor` with an exemplary addup in docs about a way to spawn process with `stem` if one wants to?
> And it is possible to use the external Tor proxy using the `singleProxy` approach (instead of the `tor_external`), without losing much functionality.

One would think that ability to change tor chain matters. Is there a way to get some logging from proxies? More info from scholarly with tunable loglevel would simplify finding out problems (but i suppose, the last sentence should go to another issue)
