### ISSUE TITLE
Full abstact of the paper is not available

### ISSUE THREAD

**Issue by azkhadiev** [scholarly-python-package/scholarly#435]
**Describe the bug**
I was trying to get the full abstract by the scholarly from the certain paper, but the data in the ['bib']['abstract'] was not full.

**To Reproduce**
search_query = scholarly.search_pubs('10.1021/acsnano.1c03002')
pub_data= scholarly.fill(next(search_query))
print(pub_data['bib']['abstract'])

**Expected behavior**
Expected to have a full abstract of the paper

**Comment by arunkannawadi** [comment]
The abstract is truncated on the GS page here: https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0%2C33&q=10.1021%2Facsnano.1c03002&btnG=

So it is not a bug with `scholarly` that the fetched abstract is not full. If you can find a Google Scholar page with a full abstract of the paper, post it here and we could add a feature to fetch that automatically in a future release. Otherwise, we'll have to consider the issue invalid and closed.

For now, you can look for the same publication through one of the author profiles (they can be found in `pub_data['author_id']`. The abstract is still truncated, but at least it contains the larger portion of the abstract.
https://scholar.google.com/citations?view_op=view_citation&hl=en&user=edUX-DYAAAAJ&cstart=20&pagesize=80&citation_for_view=edUX-DYAAAAJ:8k81kl-MbHgC

**Comment by firmianay** [comment]
When using Google Scholar on my mobile phone, I can click on the title to see the full summary. The URL is as follows, but if I copy it to the desktop and open it, it will return to the previous page. Maybe you can modify the request header to achieve this requirement.

https://scholar.google.com/scholar?hl=zh-CN&as_sdt=0%2C5&q=I+Can+See+the+Light%3A+Attacks+on+Autonomous+Vehicles+Using+Invisible+Lights.&btnG=#d=gs_qabs&t=1684390477808&u=%23p%3DwbIcC8m93EwJ

**Comment by endeavormoquan** [comment]
refer to https://github.com/amirbabaei97/paper_scrapper/blob/main/scraper.py#L166. After this line, all the elements can be dumped to extract the abstract. Remember to set the backoff carefully to avoid blocking.
