### ISSUE TITLE
scholarly.search_pubs(query) \n pprint(query) is parsings and returning only 1st result of the page

### ISSUE THREAD

**Issue by amani-acog** [scholarly-python-package/scholarly#504]
search_query = scholarly.search_pubs(query)
scholarly.pprint(next(search_query))

I am using above method to get the data of research publications it is parsing and returning only 1st result of the page

**Comment by arunkannawadi** [comment]
Yes, that is the intended output. For the next result, you need to run the second line again, especially the `next` call. Alternatively (and *not* recommended), you can call `list(search_query)`, but if there are many many pages and you don't need them all, you'll likely hit an error due to Google Scholar blocking your search.
