### ISSUE TITLE
Use Tor directly through stem instead of requiring separate installation of Tor client

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#94]
Given that Tor gives substantial improvements in stability, we should consider using Tor directly from stem, without the need to have a separately installed Tor client. That will simplify installation across platforms, and will also transparently improve the stability of the package.

**Comment by ipeirotis** [comment]
So, here is the idea.

We have the following options, in decreasing order of preference/stability

1. `use_own_tor `: Launch Tor (with a control port) using stem within scholarly. The launched Tor gets shut down when scholarly exits. This allows for scholarly to refresh Tor id's without having to worry about external setup for torrc, passwords, etc.

2. `use_refreshable_tor`: Use Tor with a control port that allows for refreshable ids. Same as (1), but we need to setup a torrc and have proper authentication for the control port to allow for the refresh.

3. `tor_proxy_only` Use Tor without refresh. Very similar to using any old proxy. Cannot refresh id if something goes wrong and scholar blocks the node

4. `refreshable_proxy`: We can use a list of proxies (e.g., from FreeProxy) and go through them if we ran into an issue. Early experiments were not very promising as these proxies get flagged very quickly (more often than Tor nodes) as they get used by many apps. But better than nothing.

5. `regular_proxy`: User selects a proxy server

6. `no_proxies`: Direct connection to Google Scholar.

I have also taken a quick look at `torpy` that does not require a separate installation of Tor. It was not as stable as the solution that relies on the official Tor distribution. But we can experiment and see. If `torpy` works, then it may be the most clean approach, as it would not require any additional setup for the user.

**Comment by silvavn** [comment]
I think we should implement 1, 2, 5 and 6.

1. Will mostly work for linux users, will allow better control and would be great if we can adapt to other systems

2. Actually 2 should be standard if we are using Tor. 

3.  I don't think there is a point in using only one tor node since the agent would be stuck at some point.

4. If 5 is implemented, then 4 is easy to implement outside of scholarly.

5. Should be implemented so users can pass their tor or own proxy.

6. If user cant run 1 nor 5, then this should be an option. Also, this should include a selenium version since captchas may show up eventually.

**Comment by ipeirotis** [comment]
I am also leaning towards removing any "automatic", behind the scenes discovery of Tor, launch of Tor processes, and so on.

We should have example code snippets showcasing how to use the above options, and let users "debug" any issues that may arise.
